/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pras
 */
public class Absen extends javax.swing.JFrame {

    /**
     * Creates new form Absen
     */

    private void autoid(){
        try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dblogin","root","");
                
                // Menggunakan Statement untuk mengeksekusi perintah SQL
                String sql = "SELECT * FROM mhs ORDER BY NIM DESC";
                Statement stmt = con.createStatement();
                
                ResultSet rs = stmt.executeQuery(sql);
                
                if (rs.next()) {
                    String NIM = rs.getString("NIM");
                    String id = NIM.substring(0);
                    txid.setText(id);
                    
                } else {
                    // Jika tidak ada data di tabel 'mhs', atur nilai default
                    txid.setText("error");
                }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada Error");
        }
    }   

    CardLayout cardLayout;
    public Absen() {
        initComponents();
        show_combo();
        show_comboo();
        show_combo2();
        show_combo3();
        show_combo4();
        show_combo5();
        show_combo6();
        autoid();
        show_data();
        show_data1();
        show_data2();
        
        cardLayout = (CardLayout)(jPanel2.getLayout());
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mhs = new javax.swing.JComboBox<>();
        matkul = new javax.swing.JComboBox<>();
        pertemuan = new javax.swing.JComboBox<>();
        ket = new javax.swing.JComboBox<>();
        sbmt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txid = new javax.swing.JTextField();
        rfrsh = new javax.swing.JToggleButton();
        card3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        mhs1 = new javax.swing.JComboBox<>();
        matkul1 = new javax.swing.JComboBox<>();
        prtmn = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        card4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        mhs2 = new javax.swing.JComboBox<>();
        matkul2 = new javax.swing.JComboBox<>();
        prtmn1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 184, 39));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 288));

        jPanel3.setBackground(new java.awt.Color(253, 184, 39));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/icons8_world_map_105px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(253, 184, 39));

        jButton6.setBackground(new java.awt.Color(252, 213, 129));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/icons8_home_45px_2.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(253, 184, 39));

        jButton7.setBackground(java.awt.Color.orange);
        jButton7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/icons8_copybook_45px_1.png"))); // NOI18N
        jButton7.setText("Absensi");
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(253, 184, 39));

        jButton8.setBackground(java.awt.Color.orange);
        jButton8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/icons8_copybook_45px_1.png"))); // NOI18N
        jButton8.setText("Rekap Mingguan");
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(253, 184, 39));

        jButton9.setBackground(java.awt.Color.orange);
        jButton9.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/icons8_copybook_45px_1.png"))); // NOI18N
        jButton9.setText("Rekap Bulanan");
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(253, 184, 39));

        jButton10.setBackground(java.awt.Color.orange);
        jButton10.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/icons8_copybook_45px_1.png"))); // NOI18N
        jButton10.setText("Admin");
        jButton10.setBorder(null);
        jButton10.setContentAreaFilled(false);
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(58, 71, 80));
        jPanel2.setLayout(new java.awt.CardLayout());

        card1.setBackground(new java.awt.Color(58, 71, 80));

        jLabel1.setBackground(new java.awt.Color(245, 245, 245));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Selamat Datang");

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(444, Short.MAX_VALUE))
        );

        jPanel2.add(card1, "card1");
        card1.getAccessibleContext().setAccessibleName("card1");

        card2.setBackground(new java.awt.Color(58, 71, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        mhs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mhsItemStateChanged(evt);
            }
        });
        mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsActionPerformed(evt);
            }
        });

        matkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkulActionPerformed(evt);
            }
        });

        pertemuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        pertemuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertemuanActionPerformed(evt);
            }
        });

        ket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Izin", "Alpha" }));

        sbmt.setText("SUBMIT");
        sbmt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("IDMatkul");

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Pertemuan");

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Keterangan");

        txid.setEnabled(false);
        txid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidActionPerformed(evt);
            }
        });

        rfrsh.setText("Refresh");
        rfrsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfrshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(card2Layout.createSequentialGroup()
                                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(card2Layout.createSequentialGroup()
                                        .addComponent(mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(card2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sbmt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pertemuan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rfrsh))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                        .addComponent(txid, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pertemuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(rfrsh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbmt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        txid.getAccessibleContext().setAccessibleName("txid");

        jPanel2.add(card2, "card2");
        card2.getAccessibleContext().setAccessibleName("card2");

        card3.setBackground(new java.awt.Color(58, 71, 80));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        mhs1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        mhs1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mhs1ItemStateChanged(evt);
            }
        });

        matkul1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));

        prtmn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023-12-03 - 2023-12-09", "2023-12-12 - 2023-12-16", "2023-12-17 - 2023-12-23", "2023-12-24 - 2023-12-30", "2023-12-31 - 2024-01-06", "2024-01-07 - 2024-01-13", "2024-01-14 - 2024-01-20", "2024-01-21 - 2024-01-27", "2024-01-28 - 2024-02-03" }));
        prtmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prtmnActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PER - MINGGU");

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nama");

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Matkul");

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pertemuan");

        javax.swing.GroupLayout card3Layout = new javax.swing.GroupLayout(card3);
        card3.setLayout(card3Layout);
        card3Layout.setHorizontalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(card3Layout.createSequentialGroup()
                        .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mhs1, 0, 130, Short.MAX_VALUE))
                        .addGap(104, 104, 104)
                        .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(matkul1, 0, 130, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prtmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        card3Layout.setVerticalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mhs1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matkul1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prtmn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        jPanel2.add(card3, "card3");
        card3.getAccessibleContext().setAccessibleName("card3");

        card4.setBackground(new java.awt.Color(58, 71, 80));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        mhs2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        mhs2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mhs2ItemStateChanged(evt);
            }
        });

        matkul2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));

        prtmn1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023-12-01 - 2023-12-31", "2024-01-01 - 2024-01-30", "2024-02-01 - 2024-02-29" }));
        prtmn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prtmn1ActionPerformed(evt);
            }
        });

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PER - BULAN");

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nama");

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Matkul");

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Pertemuan");

        javax.swing.GroupLayout card4Layout = new javax.swing.GroupLayout(card4);
        card4.setLayout(card4Layout);
        card4Layout.setHorizontalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addGroup(card4Layout.createSequentialGroup()
                        .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mhs2, 0, 130, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104)
                        .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(matkul2, 0, 130, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prtmn1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        card4Layout.setVerticalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mhs2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matkul2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prtmn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        jPanel2.add(card4, "card4");
        card4.getAccessibleContext().setAccessibleName("card4");

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void show_combo(){
        try {
            String sql = "SELECT * FROM mhs";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                mhs.addItem(rs.getString("nama"));
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }
    
    private String mtkl_plhn1(JComboBox a) {
        String hsl = "";
        try {
            String sql = "SELECT * FROM matkul WHERE nama_matkul='"+a.getSelectedItem()+"'";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                String result = rs.getString(7);
                hsl = result;
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        } 
    return hsl;
    }
    
    private String mtkl_plhn2(JComboBox a) {
        String hsl = "";
        try {
            String sql = "SELECT * FROM matkul WHERE nama_maktul='"+a.getSelectedItem()+"'";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                String result = rs.getString(8);
                hsl = result;
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        } 
    return hsl;
    }
    
    private String mtkl_plhn3(JComboBox a) {
        String hsl = "";
        try {
            String sql = "SELECT * FROM matkul WHERE nama_matkul='"+a.getSelectedItem()+"'";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                String result = rs.getString(9);
                hsl = result;
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        } 
    return hsl;
    }

    private void show_combo1(){
        if (matkul.getItemCount() > 1 ){
            matkul.removeItemAt(3);
            matkul.removeItemAt(2);
            matkul.removeItemAt(1);
        }
        try {
            String sql = "SELECT * FROM matkul WHERE nama_matkul = '"+mtkl_plhn1(matkul)+"' OR nama_matkul = '"+mtkl_plhn2(matkul)+ "' OR nama_matkul = '"+mtkl_plhn3(matkul)+"'";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                
                matkul.addItem(rs.getString("nama_matkul"));
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }

    private void show_combo2(){
        try {
            String sql = "SELECT * FROM pertemuan";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                pertemuan.addItem(rs.getString("tgl"));
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }    
    
    private void show_combo3(){
        try {
            String sql = "SELECT * FROM mhs";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                mhs1.addItem(rs.getString("nama"));
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }    
    
    private void show_combo4(){
        try {
            String sql = "SELECT * FROM matkul";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                matkul1.addItem(rs.getString("nama_matkul"));
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }
    
    private void show_comboo(){
        try {
            String sql = "SELECT * FROM matkul";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                matkul.addItem(rs.getString("nama_matkul"));
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }

    private void show_combo5(){
        try {
            String sql = "SELECT * FROM mhs";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                mhs2.addItem(rs.getString("nama"));
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }    
    
    private void show_combo6(){
        try {
            String sql = "SELECT * FROM matkul";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                
                matkul2.addItem(rs.getString("nama_matkul"));
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        }
    }
        
    
    public String chooseid(JComboBox a){
        String hsl = "";
        try {
            String sql = "SELECT * FROM mhs WHERE Nama='"+a.getSelectedItem()+"'";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                String result = rs.getString(2);
                hsl = result;
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        } 
    return hsl;
    }
    
    public String chooseid1(JComboBox a){
        String hsl = "";
        try {
            String sql = "SELECT * FROM matkul WHERE nama_matkul='"+a.getSelectedItem()+"'";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                String result = rs.getString(1);
                hsl = result;
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            e.printStackTrace();
        } 
    return hsl;
    }

    public String chooseid2(JComboBox a){
        String hsl = "";
        try {
            String sql = "SELECT * FROM pertemuan WHERE tgl ='"+a.getSelectedItem()+"'";
            java.sql.Connection con= (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                String result = rs.getString(1);
                hsl = result;
                
            }
            rs.last();
            int data = rs.getRow();
            rs.first();
            
        }catch(Exception e){
            
        } 
    return hsl;
    }

    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        cardLayout.show(jPanel2, "card2");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        setColorLeft(jPanel5);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        resetColorLeft(jPanel5);
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        setColorLeft(jPanel4);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        resetColorLeft(jPanel4);
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        setColorLeft(jPanel7);
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        resetColorLeft(jPanel7);
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        setColorLeft(jPanel8);
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        resetColorLeft(jPanel8);
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        cardLayout.show(jPanel2, "card1");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        cardLayout.show(jPanel2, "card3");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        cardLayout.show(jPanel2, "card4");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mhsActionPerformed

    private void txidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidActionPerformed

    private void sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtActionPerformed
        
        try {
            String sql = "INSERT INTO absen VALUES ('"
                    +txid.getText()+"','"
                    +chooseid(mhs)+"','"
                    +chooseid1(matkul)+"','"
                    +chooseid2(pertemuan)+"','"
                    +ket.getSelectedItem()+"')";
            java.sql.Connection con = (java.sql.Connection) Home.Koneksi.getKoneksi();
            java.sql.PreparedStatement stmnt = con.prepareStatement(sql);
            stmnt.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
            show_data();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Disimpan");
            System.out.println(e.getMessage()); 
        }
    }//GEN-LAST:event_sbmtActionPerformed
    
    public void show_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("NIM");
        tabel.addColumn("Nama");
        tabel.addColumn("Matkul");
        tabel.addColumn("Pertemuan");
        tabel.addColumn("Ket");
        try {
            java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
            String sql = "SELECT mhs.NIM, mhs.Nama, matkul.nama_matkul, pertemuan.tgl, absen.ket FROM absen LEFT JOIN mhs ON absen.NIM = mhs.NIM LEFT JOIN matkul ON absen.nama_matkul = matkul.nama_matkul LEFT JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan";
            java.sql.PreparedStatement stm = con.prepareStatement(sql);
            ResultSet rs =stm.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                }
            jTable1.setModel(tabel);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error bro");
                System.out.println(e.getMessage());
            }
    }
    
    public String tgl_between(JComboBox a) {
	String myString = a.getSelectedItem().toString();
        String[] splitString = myString.split(" - ");
        String st1 = splitString[0];
        String st2 = splitString[1];
        String hsl = st1+"'"+" AND "+"'"+st2;
    return hsl;
    }
    
    public void scndtable(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("NIM");
        tabel.addColumn("Nama");
        tabel.addColumn("Hadir");
        tabel.addColumn("Izin");
        tabel.addColumn("Alpha");
        try {
            java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
            String sql = "SELECT mhs.NIM, mhs.nama, SUM(absen.ket = 'Hadir' AND absen.nama_matkul = '"+chooseid1(matkul1)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"'), SUM(absen.ket = 'Izin' AND absen.nama_matkul = '"+chooseid1(matkul1)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"'), SUM(absen.ket = 'Alpha' AND absen.nama_matkul = '"+chooseid1(matkul1)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"') FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan GROUP BY mhs.NIM;";
            System.out.println(sql);
            java.sql.PreparedStatement stm = con.prepareStatement(sql);
            ResultSet rs =stm.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5)});
            }
            jTable3.setModel(tabel);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error bro");
            System.out.println(e.getMessage());
        }
    }
    
    public void scndtable1(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("NIM");
        tabel.addColumn("Nama");
        tabel.addColumn("Hadir");
        tabel.addColumn("Izin");
        tabel.addColumn("Alpha");
        try {
            java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
            String sql = "SELECT mhs.NIM, mhs.nama, SUM(absen.ket = 'Hadir' AND absen.nama_matkul = '"+chooseid1(matkul2)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"'), SUM(absen.ket = 'Izin' AND absen.nama_matkul = '"+chooseid1(matkul2)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"'), SUM(absen.ket = 'Alpha' AND absen.nama_matkul = '"+chooseid1(matkul2)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"') FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan GROUP BY mhs.NIM;";
            System.out.println(sql);
            java.sql.PreparedStatement stm = con.prepareStatement(sql);
            ResultSet rs =stm.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5)});
            }
            jTable5.setModel(tabel);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error bro");
            System.out.println(e.getMessage());
        }
    }
    
    
    public void show_data1(){
        if (mhs1.getSelectedItem() == "-SELECT-" && matkul1.getSelectedItem() == "-SELECT-"){
            String sql = "";
            DefaultTableModel tabel = new DefaultTableModel();
            tabel.addColumn("Keterangan");
            tabel.addColumn("Jumlah Total");
            try {
                java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
                sql = "SELECT absen.ket, COUNT(*) FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan WHERE pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"' GROUP BY absen.ket;";
                System.out.println(sql);
                java.sql.PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs =stm.executeQuery(sql);
                while (rs.next()) {
                    tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2)});
                    }
                jTable2.setModel(tabel);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Error bro");
                    System.out.println(e.getMessage());
                }
        } else if (mhs1.getSelectedItem() == "-SELECT-" && matkul1.getSelectedItem() != "-SELECT-") {
            String sql = "";
            DefaultTableModel tabel = new DefaultTableModel();
            tabel.addColumn("Keterangan");
            tabel.addColumn("Jumlah Total");
            try {
                java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
                sql = "SELECT absen.ket, COUNT(*) FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan WHERE pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"' AND matkul.nama_matkul = '"+chooseid1(matkul1)+"' GROUP BY absen.ket;";
                System.out.println(sql);
                java.sql.PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs =stm.executeQuery(sql);
                while (rs.next()) {
                    tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2)});
                    }
                scndtable();
                jTable2.setModel(tabel);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Error bro");
                    System.out.println(e.getMessage());
                }
            
        } else {
            DefaultTableModel tabel = new DefaultTableModel();
            tabel.addColumn("NIM");
            tabel.addColumn("Nama");
            tabel.addColumn("Hadir");
            tabel.addColumn("Izin");
            tabel.addColumn("Alpha");
            try {
                java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
                String sql = "SELECT mhs.NIM, mhs.Nama, SUM(absen.ket = 'Hadir' AND absen.Nama = '"+chooseid(mhs1)+"' AND matkul.nama_matkul = '"+chooseid1(matkul1)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"'), SUM(absen.ket = 'Izin' AND absen.Nama = '"+chooseid(mhs1)+"' AND matkul.nama_matkul = '"+chooseid1(matkul1)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"'), SUM(absen.ket = 'Alpha' AND absen.Nama = '"+chooseid(mhs1)+"' AND matkul.nama_matkul = '"+chooseid1(matkul1)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn) +"') FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan WHERE absen.Nama = '"+chooseid(mhs1)+"' GROUP BY mhs.NIM;";
                System.out.println(sql);
                java.sql.PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs =stm.executeQuery(sql);
                while (rs.next()) {
                    tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5)});
                    }
                scndtable();
                jTable2.setModel(tabel);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Error bro");
                    System.out.println(e.getMessage());
                }
        }
    }
    
    public void show_data2(){
        if (mhs2.getSelectedItem() == "-SELECT-" && matkul2.getSelectedItem() == "-SELECT-"){
            String sql = "";
            DefaultTableModel tabel = new DefaultTableModel();
            tabel.addColumn("Keterangan");
            tabel.addColumn("Jumlah Total");
            try {
                java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
                sql = "SELECT absen.ket, COUNT(*) FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan WHERE pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"' GROUP BY absen.ket;";
                System.out.println(sql);
                java.sql.PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs =stm.executeQuery(sql);
                while (rs.next()) {
                    tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2)});
                    }
                jTable4.setModel(tabel);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Error bro");
                    System.out.println(e.getMessage());
                }
        } else if (mhs2.getSelectedItem() == "-SELECT-" && matkul2.getSelectedItem() != "-SELECT-") {
            String sql = "";
            DefaultTableModel tabel = new DefaultTableModel();
            tabel.addColumn("Keterangan");
            tabel.addColumn("Jumlah Total");
            try {
                java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
                sql = "SELECT absen.ket, COUNT(*) FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan WHERE pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"' AND matkul.nama_matkul = '"+chooseid1(matkul2)+"' GROUP BY absen.ket;";
                System.out.println(sql);
                java.sql.PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs =stm.executeQuery(sql);
                while (rs.next()) {
                    tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2)});
                    }
                scndtable1();
                jTable4.setModel(tabel);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Error bro");
                    System.out.println(e.getMessage());
                }
            
        } else {
            DefaultTableModel tabel = new DefaultTableModel();
            tabel.addColumn("NIM");
            tabel.addColumn("Nama");
            tabel.addColumn("Hadir");
            tabel.addColumn("Izin");
            tabel.addColumn("Alpha");
            try {
                java.sql.Connection con = (java.sql.Connection)Home.Koneksi.getKoneksi();
                String sql = "SELECT mhs.NIM, mhs.nama, SUM(absen.ket = 'Hadir' AND absen.NIM = '"+chooseid(mhs2)+"' AND matkul.nama_matkul = '"+chooseid1(matkul2)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"'), SUM(absen.ket = 'Izin' AND absen.NIM = '"+chooseid(mhs2)+"' AND matkul.nama_matkul = '"+chooseid1(matkul2)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"'), SUM(absen.ket = 'Alpha' AND absen.NIM = '"+chooseid(mhs2)+"' AND matkul.nama_matkul = '"+chooseid1(matkul2)+"' AND pertemuan.tgl BETWEEN '"+ tgl_between(prtmn1) +"') FROM mhs JOIN absen ON mhs.NIM = absen.NIM JOIN matkul ON absen.nama_matkul = matkul.nama_matkul JOIN pertemuan ON absen.id_pertemuan = pertemuan.id_pertemuan WHERE absen.NIM = '"+chooseid(mhs2)+"' GROUP BY mhs.NIM;";
                System.out.println(sql);
                java.sql.PreparedStatement stm = con.prepareStatement(sql);
                ResultSet rs =stm.executeQuery(sql);
                while (rs.next()) {
                    tabel.addRow(new Object[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5)});
                    }
                scndtable1();
                jTable4.setModel(tabel);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Error bro");
                    System.out.println(e.getMessage());
                }
        }
    }
    
    
    private void matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkulActionPerformed
        show_comboo();
    }//GEN-LAST:event_matkulActionPerformed

    private void mhsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mhsItemStateChanged
        show_data();
        show_combo1();
    }//GEN-LAST:event_mhsItemStateChanged

    private void pertemuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertemuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pertemuanActionPerformed

    private void rfrshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfrshActionPerformed
        show_data();
        show_combo1();
    }//GEN-LAST:event_rfrshActionPerformed

    private void mhs1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mhs1ItemStateChanged
        show_data1();
    }//GEN-LAST:event_mhs1ItemStateChanged

    private void prtmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prtmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prtmnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        show_data1();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        show_data2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void prtmn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prtmn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prtmn1ActionPerformed

    private void mhs2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mhs2ItemStateChanged
        show_data2();
    }//GEN-LAST:event_mhs2ItemStateChanged

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        setColorLeft(jPanel9);
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        resetColorLeft(jPanel9);
    }//GEN-LAST:event_jButton10MouseExited

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
        Admin a = new Admin();
        a.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed
    public void setColor(JPanel p) {
        p.setBackground(new Color(124,146,160));
    }
    public void setColorLeft(JPanel p) {
        p.setBackground(new Color(252,213,129));
    }
    public void setColorRed(JPanel p) {
        p.setBackground(new Color(255,0,0));
    }
    public void resetColor(JPanel p1) {
        p1.setBackground(new Color(58,71,80));
    }
    public void resetColorLeft(JPanel p1) {
        p1.setBackground(new Color(253,184,39));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel card4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JComboBox<String> ket;
    private javax.swing.JComboBox<String> matkul;
    private javax.swing.JComboBox<String> matkul1;
    private javax.swing.JComboBox<String> matkul2;
    private javax.swing.JComboBox<String> mhs;
    private javax.swing.JComboBox<String> mhs1;
    private javax.swing.JComboBox<String> mhs2;
    private javax.swing.JComboBox<String> pertemuan;
    private javax.swing.JComboBox<String> prtmn;
    private javax.swing.JComboBox<String> prtmn1;
    private javax.swing.JToggleButton rfrsh;
    private javax.swing.JButton sbmt;
    private javax.swing.JTextField txid;
    // End of variables declaration//GEN-END:variables
}